pipeline {
    agent none

    triggers {
        pollSCM('* * * * *')
    }

    stages {
        stage("Compile") {
            agent { docker { image 'gradle:7.6-jdk11' } }
            steps {
                dir('sample3') {
                    sh "gradle compileJava"
                }
            }
        }

        stage("Unit test") {
            agent { docker { image 'gradle:7.6-jdk11' } }
            steps {
                dir('sample3') {
                    sh "gradle test"
                }
            }
        }

        stage("Code coverage") {
            agent { docker { image 'gradle:7.6-jdk11' } }
            steps {
                dir('sample3') {
                    sh "gradle jacocoTestReport"

                    publishHTML(target: [
                        reportDir: 'build/reports/jacoco/test/html',
                        reportFiles: 'index.html',
                        reportName: "JaCoCo Report"
                    ])

                    sh "gradle jacocoTestCoverageVerification"
                }
            }
        }

        stage("Static code analysis") {
            agent { docker { image 'gradle:7.6-jdk11' } }
            steps {
                dir('sample3') {
                    sh "gradle checkstyleMain"

                    publishHTML(target: [
                        reportDir: 'build/reports/checkstyle',
                        reportFiles: 'main.html',
                        reportName: "Checkstyle Report"
                    ])
                }
            }
        }
    }
}
