pipeline {
    agent none

    stages {
        stage("Compile") {
            agent { docker { image 'gradle:7.6-jdk11' } }
            steps {
                dir('sample2') {
                    sh "gradle compileJava"
                }
            }
        }

        stage("Unit test") {
            agent { docker { image 'gradle:7.6-jdk11' } }
            steps {
                dir('sample2') {
                    sh "gradle test"
                }
            }
        }

        stage("Code coverage") {
          agent { docker { image 'gradle:7.6-jdk11' } }
          steps {
               dir('sample2') {
                    sh "gradle jacocoTestReport"

                    publishHTML(target: [
                         reportDir: 'build/reports/jacoco/test/html',
                         reportFiles: 'index.html',
                         reportName: "JaCoCo Report"
                    ])

                    sh "gradle jacocoTestCoverageVerification"
               }
          }
     }
    }
}